dora:
  camera:
    opencv:
      default_params:
        path: ../../components/camera_opencv/main.py
        period: 30
        width: 640
        height: 480
        output:  
          - image
        encoding: "bgr8"
      outputs_info:
        image:
          width: 640
          height: 480
          channels: 3

    realsense:
      default_params:
        path: ../../components/camera_rgbd_realsense/main.py
        period: 30
        width: 640
        height: 480
        device_serial: ""
        output:  
          - image
          - image_depth
        encoding: "bgr8"
      outputs_info:
        image:
          width: 640
          height: 480
          channels: 3
        image_depth:
          width: 640
          height: 480
          channels: 3
    
    orbbec:
      default_params:
        path: ../../components/camera_rgbd_orbbec/main.py
        period: 30
        width: 640
        height: 480
        device_serial: ""
        output:  
          - image
          - image_depth
        encoding: "bgr8"
      outputs_info:
        image:
          width: 640
          height: 480
          channels: 3
        image_depth:
          width: 640
          height: 480
          channels: 3

    zed:
      default_params:
        path: ../../components/camera_rgbd_zed/main.py
        period: 30
        width: 640
        height: 480
        device_serial: ""
        output:  
          - image_left
          - image_right
        encoding: "bgr8"
      outputs_info:
        image_left:
          width: 640
          height: 480
          channels: 3
        image_right:
          width: 640
          height: 480
          channels: 3

  arm:
    robot_arm:
      default_params:
        path: ../../components/robot_arm/main.py
        period: 30
        output:
          - pose
      outputs_info:
        pose:
          motors:
            joint_1: [1, "piper-motor"]
            joint_2: [2, "piper-motor"]
            joint_3: [3, "piper-motor"]
            joint_4: [4, "piper-motor"]
            joint_5: [5, "piper-motor"]
            joint_6: [6, "piper-motor"]
            pose_x:  [7, "piper-pose"]
            pose_y:  [8, "piper-pose"]
            pose_z:  [9, "piper-pose"]
            pose_rx: [10, "piper-pose"]
            pose_ry: [11, "piper-pose"]
            pose_rz: [12, "piper-pose"]
            gripper: [13, "piper-gripper"]

ros:
  camera:
    opencv:
      default_params:
        topic: ""
        msgs: ""
        period: 30
        output:
          - image
      outputs_info:
        image:
          width: 640
          height: 480
          channels: 3
    
    realsense:
      default_params:
        topic: ""
        msgs: ""
        period: 30
        output: 
          - image
          - image_depth
      outputs_info:
        image:
          width: 640
          height: 480
          channels: 3
        image_depth:
          width: 640
          height: 480
          channels: 3

    orbbec:
      default_params:
        topic: ""
        msgs: ""
        period: 30
        output: 
          - image
          - image_depth
      outputs_info:
        image:
          width: 640
          height: 480
          channels: 3
        image_depth:
          width: 640
          height: 480
          channels: 3

  arm:
    robotera_pose:
      default_params:
        topic: ""
        msgs: ""
        period: 30
        output:
          - pose
      outputs_info:
        pose:
          motors:
            "position_x": [1, "robotera_motor"]
            "position_y": [2, "robotera_motor"]
            "position_z": [3, "robotera_motor"]
            "orientation_x": [4, "robotera_motor"]
            "orientation_y": [5, "robotera_motor"]
            "orientation_z": [6, "robotera_motor"]
            "orientation_w": [7, "robotera_motor"]

    robotera_finger_joints:
      default_params:
        topic: ""
        msgs: ""
        period: 30
        output:
          - pose
      outputs_info:
        pose:
          motors:
            "hand_thumb_rota_joint2_position": [1, "robotera_motor"]
            "hand_index_bend_joint_position": [2, "robotera_motor"]
            "hand_pinky_joint2_position": [3, "robotera_motor"]
            "hand_index_joint1_position": [4, "robotera_motor"]
            "hand_index_joint2_position": [5, "robotera_motor"]
            "hand_mid_joint2_position": [6, "robotera_motor"]
            "hand_thumb_rota_joint1_position": [7, "robotera_motor"]
            "hand_ring_joint2_position": [8, "robotera_motor"]
            "hand_ring_joint1_position": [9, "robotera_motor"]
            "hand_thumb_bend_joint_position": [10, "robotera_motor"]
            "hand_mid_joint1_position": [11, "robotera_motor"]
            "hand_pinky_joint1_position": [12, "robotera_motor"]

    robotera_tasks_joints:
      default_params:
        topic: ""
        msgs: ""
        period: 30
        output:
          - pose
      outputs_info:
        pose:
          motors:
            "left_drv_wheel_joint": [1, "robotera_motor"]
            "left_drv_hang_joint": [2, "robotera_motor"]
            "neck_pitch_joint": [3, "robotera_motor"]
            "right_drv_wheel_joint": [4, "robotera_motor"]
            "ankle_joint": [5, "robotera_motor"]
            "neck_yaw_joint": [6, "robotera_motor"]
            "waist_yaw_joint": [7, "robotera_motor"]
            "right_drv_hang_joint": [8, "robotera_motor"]
            "hip_joint": [9, "robotera_motor"]
            "knee_joint": [10, "robotera_motor"]


